### ISSUE TITLE
The plugin does not add any check

### ISSUE THREAD

**Issue by Mahjouba91** [humanmade/publication-checklist#6]
Hello,

As explained earlier on this Issue #4 there is not any working checks.

I had a look at the DOM as you suggested, and I can see your custom component for the publish button. Otherwise, I still don't see any action when I click the publish button, it publishes directly the post without blocking anything.

Running:

- PHP 7.3 on a local Docker environment
- WordPress 5.3
- Gutenberg 6.9

Code sample I tried:
```php
add_action( 'altis.publication-checklist.register_prepublish_checks', function () {
	register_prepublish_check( 'foo', [
		'run_check' => function ( array $post, array $meta ): Status {
			var_dump( $post );
			die( 'debug' );
			if ( isset( $post ) ) {
				return new Status( Status::COMPLETE, 'Foo completed' );
			}

			return new Status( Status::INCOMPLETE, 'Missing foo data' );
		},
	] );
} );

add_action( 'altis.publication-checklist.register_prepublish_checks', function () {
	register_prepublish_check( 'title_length', [
		'run_check' => function ( array $post, array $meta ): Status {
			if ( count( $post['title'] ) < 80 ) {
				return new Status( Status::INCOMPLETE, 'Post title is too short' );
			}
			return new Status( Status::COMPLETE, 'Title long enough' );

		},
	] );
} );
```

**Comment by Mahjouba91** [comment]
Hello @rmccue, do you have any idea about the issue please ?

**Comment by rmccue** [comment]
I have been on holiday, happy new year :)

Are you certain that the code to register your actions is being run?

**Comment by Mahjouba91** [comment]
Hello @rmccue, thank you, happy new year too :)

Yes it is run in functions.php of the theme. I really don't understand why it doesn't work, it seems weird

**Comment by Mahjouba91** [comment]
Hellp @rmccue I am still unable to make the plugin work properly. I heard some friends are not able to do so as well, so I think it's a general issue and not related to my personal use case.

Do you think you'll have time to investigate a bit ?

**Comment by neverything** [comment]
@Mahjouba91 are you sure you are using the correct version of the plugin? I just installed it in a project I'm working on using composer. So make sure you are using the [release](https://github.com/humanmade/publication-checklist/releases) otherwise you are missing the `build` directory.

Here is a simple check that I implemented and it's working:

```php
add_action(
		'altis.publication-checklist.register_prepublish_checks',
		function () {
			register_prepublish_check(
				'title',
				array(
					'run_check' => function( array $post, array $meta ) : Status {
						if ( isset( $post['post_title'] ) && '' !== $post['post_title'] ) {
							return new Status( Status::COMPLETE, 'Title is set' );
						}

						return new Status( Status::INCOMPLETE, 'Missing title' );
					},
				)
			);
		}
	);
```

And I just tested your check for `title_length` and I think you meant to use `strlen()` instead of `count()` as it only counts items in an array.

```php
register_prepublish_check(
				'title_length',
				array(
					'run_check' => function ( array $post, array $meta ): Status {
						if ( strlen( $post['post_title'] ) <= 80 ) {
							return new Status( Status::INCOMPLETE, 'Post title is too short' );
						}
						return new Status( Status::COMPLETE, 'Title long enough' );

					},
				)
			);
```

**Comment by roborourke** [comment]
Thanks @neverything, closing out due to inactivity. @Mahjouba91 if the solution posted wasn't the problem feel free to reopen.

**Comment by Mahjouba91** [comment]
It's not fixed unfortunately @roborourke 

I use a custom post type named 'article'. I'm using the last release of the plugin, here's my code:

```php
add_action(
	'altis.publication-checklist.register_prepublish_checks',
	function () {
		register_prepublish_check(
			'title_length',
			[
				'type' => 'article',
				'run_check' => function ( array $post, array $meta ): Status {
					if ( strlen( $post['post_title'] ) <= 80 ) {
						return new Status( Status::INCOMPLETE, 'Post title is too short' );
					}

					return new Status( Status::COMPLETE, 'Title long enough' );

				},
			]
		);

		register_prepublish_check(
			'title',
			array(
				'type' => 'article',
				'run_check' => function( array $post, array $meta ) : Status {
					if ( isset( $post['post_title'] ) && '' !== $post['post_title'] ) {
						return new Status( Status::COMPLETE, 'Title is set' );
					}

					return new Status( Status::INCOMPLETE, 'Missing title' );
				},
			)
		);

	}
);

add_filter( 'altis.publication-checklist.block_on_failing', __return_true() );
```

Despite this, I am still able to publish any article, I don't see any warning or info from the plugin, what's wrong?

**Comment by roborourke** [comment]
Is the custom post type available in the REST API? `show_in_rest` should be set to `true` when registering the custom post type.

**Comment by roborourke** [comment]
Also `add_filter( 'altis.publication-checklist.block_on_failing', __return_true() );` should be `add_filter( 'altis.publication-checklist.block_on_failing', '__return_true' );` - the 2nd param needs to be a callback rather than the direct return value of the function.

**Comment by Mahjouba91** [comment]
Yep the show_in_rest is set to true, and I fixed the mistake you mentioned but still nothing. I'm gonna stop investigating time on this plugin and use something else I think, sorry for this.

**Comment by smeedijzer-internet** [comment]
Got the same problem, the plugin doesn't block publishing.

PHP 7.3.9
WordPress 5.5.1
Using [Bedrock](https://roots.io/bedrock/)

I see the that the button seems to be replaced with the customized one:

<div class="components-panel__body altis-publication-checklist__replacement-header is-opened"> [...] </div>

The code I'm using:

```
<?php

namespace App;

use function Altis\Workflow\PublicationChecklist\register_prepublish_check;
use Altis\Workflow\PublicationChecklist\Status;

add_action(
    'altis.publication-checklist.register_prepublish_checks',
    function () {

        var_dump('dfgdfgdfg');

        register_prepublish_check(
            'title_length',
            [
                'run_check' => function ( array $post, array $meta, array $terms ) : Status {
                    if (strlen($post['post_title']) <= 80) {
                        return new Status(Status::INCOMPLETE, 'Post title is too short');
                    }

                    return new Status(Status::COMPLETE, 'Title long enough');

                },
            ]
        );

        register_prepublish_check(
            'title',
            array(
                'run_check' => function ( array $post, array $meta, array $terms ) : Status {
                    if (isset($post['post_title']) && '' !== $post['post_title']) {
                        return new Status(Status::COMPLETE, 'Title is set');
                    }

                    return new Status(Status::INCOMPLETE, 'Missing title');
                },
            )
        );

    }
);

add_filter('altis.publication-checklist.block_on_failing', '__return_true');

```

**Comment by Mahjouba91** [comment]
I'm also using Bedrock if that can help, but it was also occurring with a non Bedrock project.

**Comment by roborourke** [comment]
@smeedijzer-internet thanks for the report. Did you have a screenshot that was uploading by any chance?

I tried your code above and I get the expected result:

|Checks not passing|Checks passing|
|-|-|
|<img width="280" alt="Screenshot 2020-09-28 at 10 39 52" src="https://user-images.githubusercontent.com/23417/94416897-54c71000-0177-11eb-9a35-7570227a936c.png">|<img width="277" alt="Screenshot 2020-09-28 at 10 40 21" src="https://user-images.githubusercontent.com/23417/94416910-598bc400-0177-11eb-878f-3f5945310bf3.png">|

The publish button is in the disabled state and can't be clicked while there are still checks to pass.

I'd be surprised if Bedrock was doing anything directly with the editor and the pieces of WP that this plugin interacts with but could be worth exploring.

Could you post a screenshot of the customised publish panel that appears?

**Comment by roborourke** [comment]
Also do you see the tick icon for the plugin in the block editor's top bar? Next to the settings gear etc? Maybe there's some JS issue.

**Comment by smeedijzer-internet** [comment]
No, I don't see the tick icon in the editor + no javascript errors.

**Comment by roborourke** [comment]
🤔 hmm. Sorry for the stupid question but you're definitely using a release zip download (there should be a `build` directory in the plugin folder)? Guessing both this plugin and your custom one definitely activated... This is mighty strange.

Are you seeing that `var_dump()` output at all? It might be related to the order of actions - `do_action( 'altis.publication-checklist.register_prepublish_checks' );` is run on the `plugins_loaded` action so if your code calls `add_action( 'altis.publication-checklist.register_prepublish_checks' )` on `plugins_loaded` or a later hook that could mean it's running too late.

**Comment by smeedijzer-internet** [comment]
The problem was related to the order of actions. Got it working with the code placed in a custom plugin (instead of in my theme). Thanks for helping me out!

Maybe the readme should mention this part:

do_action( 'altis.publication-checklist.register_prepublish_checks' ); is run on the plugins_loaded action so if your code calls add_action( 'altis.publication-checklist.register_prepublish_checks' ) on plugins_loaded or a later hook that could mean it's running too late.

**Comment by roborourke** [comment]
Ace!

Yeah I agree, I'm tempted to actually make that action run a bit later, at least on a really high priority on `plugins_loaded`. Can I ask what action you had your code hooked into?

@Mahjouba91 any chance you had the same issue regarding the order of actions? No worries if you're not sure any more - I know you moved on to trying something else out.

**Comment by smeedijzer-internet** [comment]
I placed it in functions.php file and tried adding it to 'init' and 'after_setup_theme'.

**Comment by smeedijzer-internet** [comment]
P.s. I think adding: https://github.com/humanmade/demo-publication-checklist to the readme will help to

**Comment by roborourke** [comment]
Good shout 😄

**Comment by roborourke** [comment]
@jigneshbhavani the checks are post type specific so it could be that. If both plugins are active and you are looking at posts or pages you should be seeing the checks when you go to publish the page.

It might also depend which zip you downloaded. If you downloaded the zip linked in the "Code" dropdown on the main page of this repository then it will be missing the built JavaScript and CSS files.

Try this version: https://github.com/humanmade/publication-checklist/archive/refs/tags/0.3.0.zip

I'm not sure I can help much beyond that, there are a lot of variables that could be in play like other plugins or themes that could modify parts of the block editor.

Closing this issue out as the main action item to update the docs was done, and we know checks can be added and that they work.

**Comment by jigneshbhavani** [comment]
@roborourke  You are right It was issue of post type and this works great except It doesn't reflect on live changes.
